Feature/82 test pivotgrapple hook
TheShotgunStudio/we-need-a-bigger-shotgun pull request #158
Opened 2024-11-14 11:50 UTC by IcyKoala

Closes #82 
### Summary
Added a grappling point which the player can toggle using rightclick

## Checklist
### 1. Merging
- [x] Did you select the dev branch?
### 2. File Structure
- [x] Are all scripts placed within Assets/Scripts and organized into logical categories using PascalCase (e.g., Core, Player, Level)?
- [x] Are assets like materials, textures and sound files named using lower_snake_case (e.g., diamond_pickaxe.png)?
- [x] Did the changes avoid unnecessary scene modifications? If new changes were needed for testing, were they done in Scenes/Dev/<Specification> and then discarded?
### 3. Code
- [x] Do private fields start with an underscore and use camelCase (e.g., _privateVariable)?
- [x] Are static readonly variables named using UPPER_SNAKE_CASE?
- [x] Are enum types also in UPPER_SNAKE_CASE?
- [x] Are function and variable names clear, concise, and descriptive without using unnecessary abbreviations?
- [] Are all public functions and fields documented with clear summaries where needed
- [x] Does the code maintain a strict hierarchy, ensuring objects do not fetch references themselves or their parents in the hierarchy?
- [x] Are references passed down through dependency injection as needed?Does each component only depend on its parent in the hierarchy?
- [x] Have unnecessary/testing Debug.Logs been removed?
- [x] Has commented code been removed?
### 4. Logging
- [] If possible, did you make a video and did you send it/a link to it in the feature-videos channel?

2024-11-14 14:54 UTC, ninyauwu requested changes
Okay I'm a little confused why you're trying to merge this into dev when it is by your own admission, unfinished?
Grappling should probably be its own movement state with its own movement handling because it doesn't work to great now. It's nigh impossible to slow your existing movement. I just keep spinning round round (like a record baby) forever. Also because double jumping while grappling makes little sense.
All that being said however, S-tier mechanic. Thank you, this might just save the game if all else fails.

2024-11-14 14:54 UTC, ninyauwu commented on Project/Assets/Scripts/Player/GrapplePoint.cs
> +    public void setGrapplingBody(Rigidbody connectedBody_)
PascalCase

2024-11-14 14:54 UTC, ninyauwu commented on Project/Assets/Scripts/Player/GrapplePoint.cs
> +    public void setGrappleDistance(float distance)
Same here

2024-11-14 14:54 UTC, ninyauwu commented on Project/Assets/Scripts/Player/GrapplingController.cs
> +/// NOT READY FOR MERGING
"Not ready for merging"
Then why am I reviewing this PR? lol

2024-11-14 14:54 UTC, ninyauwu commented on Project/Assets/Scripts/Player/MoveState.cs
> +        if (context.ReadValue<float>() > 0)
I'd prefer if you did context.ReadValueAsButton() because that would just give you a bool which is true if the button is pressed and false if released.

2024-11-14 15:54 UTC, IcyKoala commented on Project/Assets/Scripts/Player/GrapplingController.cs
> +/// NOT READY FOR MERGING
Forgot to remove that when using making it use the proper input pathing

2024-11-14 15:58 UTC, IcyKoala commented on Project/Assets/Scripts/Player/MoveState.cs
> +        if (context.ReadValue<float>() > 0)
Didn't know that existed, good to know

2024-11-15 12:28 UTC, ninyauwu approved these changes
Approved and merged, my friend.

2024-11-15 12:28 UTC, merged