Feature/basic enemy
TheShotgunStudio/we-need-a-bigger-shotgun pull request #18
Opened 2024-10-18 11:36 UTC by Mikko5

2024-10-18 12:07 UTC, IcyKoala requested changes
A few things to change
- The naming conventions for public and protected variables
- Adding summaries (summary, params and return) to the public functions
- please try to limit unnecessary white space a bit (see EnemyController.cs and the shoot function in specific)
- Please go through your debug logs and determine which ones are needed or not, because im not sure if the debug logs in the EnemyController are needed
- Whenever the player leaves the enemies range they instantly stop shooting and start moving after the player causing them to never shoot if the player slowly moves backwards
- The current determination for enemy range is a box around the player, but this should be a sphere around the enemy itself
- The current enemy functionality seems to be updated on the enemy instance but not on the prefab itself
- Not sure if the scripts from the pro-builder branch are gonna be overwritten if it stays like this

2024-10-20 16:20 UTC, ninyauwu reviewed
I see a couple extra issues with this PR that I'd like to add
- AttackSpeed inside ShootingEnemy.cs is not implemented, nor is it clear to me how it works based on the name alone (is it the interval between attacks, or an abstract indication of speed?)
- The bullets should be destroyed on any collision, not just with a player, otherwise every missed bullet continues to exist forever, lagging the game out
- I'm not sure if you're using FollowPosition, but given that I can't find it instanced in the scene, I'm assuming it's a junk script you were using to test something in which case I'd like for you to get rid of it
- Comments, please

One thing I do really appreciate is you use UnityEvents to determine behavior, please keep doing that :)

2024-10-21 12:19 UTC, IcyKoala requested changes
Trying a more localized commenting for the review, but tl;dr:
- Seemingly unnecessary Debug logs
- Bullets not getting killed on any collision (walls and stuff)
- magic numbers (numbers with no context as to what for/annoying to find and modify because they are in the middle of the code rather than a central location)
- Some of Mats scripts should be removed so there won't be version conflics with them

2024-10-21 12:19 UTC, IcyKoala commented on Project/Assets/Scripts/Enemy/ShootingEnemy/ShootingEnemy.cs
> +        shootBullet.GetComponent<Rigidbody>().velocity = transform.forward * 25f;
Please try to avoid magic numbers, making it a variable helps other people understand better and makes editing them easier.

2024-10-21 12:19 UTC, IcyKoala commented on Project/Assets/Scripts/Recoil.cs
This script should be removed

2024-10-21 12:19 UTC, IcyKoala commented on Project/Assets/Scripts/SoundEffectManager.cs
Prolly this one as well

2024-10-21 12:19 UTC, IcyKoala commented on Project/Assets/Scripts/Enemy/ShootingEnemy/ShootingEnemy.cs
Try to remove the Debugs if there is a visual indication that the function is happening/there is no need for them

2024-10-21 13:01 UTC, IcyKoala requested changes
Please also fix the warnings that occur

2024-10-21 14:01 UTC, IcyKoala requested changes
Everything looks great, there is unfortunately one more thing.
There currently is a merge conflict with dev, so if you could merge dev into your branch and resolve the conflict that would be great.

2024-10-22 09:07 UTC, IcyKoala approved these changes
Merge conflict resolved

2024-10-22 09:07 UTC, merged