Feature/blocktober level
TheShotgunStudio/we-need-a-bigger-shotgun pull request #78
Opened 2024-10-24 11:29 UTC by IcyKoala

Closes No linked issue
### Summary
Sorry for the amount in this one
- added the blocktober scene
- organised prefabs
- animated doors
- implemented different features into one level

## Checklist
### 1. Merging
- [] Did you select the dev branch?
### 2. File Structure
- [] Are all scripts placed within Assets/Scripts and organized into logical categories using PascalCase (e.g., Core, Player, Level)?
- [] Are assets like materials, textures and sound files named using lower_snake_case (e.g., diamond_pickaxe.png)?
- [] Did the changes avoid unnecessary scene modifications? If new changes were needed for testing, were they done in Scenes/Dev/<Specification> and then discarded?
### 3. Code
- [] Do private fields start with an underscore and use camelCase (e.g., _privateVariable)?
- [] Are static readonly variables named using UPPER_SNAKE_CASE?
- [] Are enum types also in UPPER_SNAKE_CASE?
- [] Are function and variable names clear, concise, and descriptive without using unnecessary abbreviations?
- [] Are all public functions and fields documented with clear summaries where needed
- [] Does the code maintain a strict hierarchy, ensuring objects do not fetch references themselves or their parents in the hierarchy?
- [] Are references passed down through dependency injection as needed?Does each component only depend on its parent in the hierarchy?
- [] Are there any unnecessary Debug.Logs?
### 4. Logging
- [] If possible, did you make a video and did you send it/a link to it in the feature-videos channel?

2024-10-25 10:29 UTC, ninyauwu requested changes
Looks good, just implement requested changes.

2024-10-25 10:29 UTC, ninyauwu commented on Project/Assets/Scripts/Deprecated/(Deprecated) WeaponHitDetection.cs
> +        // Instantiate(DebugPelletHitIndicator, target.point, Quaternion.identity);
Could you make this into a toggle?

2024-10-25 10:29 UTC, ninyauwu commented on Project/Assets/Scripts/PlayerController.cs
> +        Cursor.lockState = CursorLockMode.Confined; //TODO find proper location for this
Move this to InputHandler and set it from the MoveState, as there may be player states where the cursor shouldn't be locked (such as UsingUIState for example).

2024-10-25 11:18 UTC, IcyKoala commented on Project/Assets/Scripts/PlayerController.cs
> +        Cursor.lockState = CursorLockMode.Confined; //TODO find proper location for this
Removed it:
I think it's then best to leave that to an issue with someone properly working in rather than a quick solution from me.

2024-10-31 10:45 UTC, ninyauwu approved these changes
Looks fine. I assume UpgradeMachine is still placeholder but I'll accept it.

2024-10-31 10:53 UTC, merged